[package]
name = "mech"
version = "0.1.0"
edition = "2021"
resolver = "2" 

[dependencies]
    anyhow = "1.0"
    serde = { version = "1.0", features = ["derive"] }
    derive_builder = "0.20.1"
    wgpu = "22.1.0"
    graph = { path = "../../core/graph" }
    gpu = { path = "../gpu" }
    node_derive = { path = "../../core/node_derive" }
    star = { path = "../../core/star" }

[dev-dependencies]
    gui = { workspace = true }
    tokio = { workspace = true }

[[test]]
    name = "live_tests"
    path = "live_tests/main.rs"
    harness = false