[package]
name = "mech"
version = "0.1.0"
edition = "2021"
resolver = "2" 

[dependencies]
    anyhow = "1.0"
    typenum = { workspace = true }
    generic-array = { workspace = true }
    derive_builder = { workspace = true }
    graph = { workspace = true }
    gpu = { workspace = true }
    star = { workspace = true }

[dev-dependencies]
    gui = { workspace = true }
    tokio = { workspace = true }

[[test]]
    name = "live_tests"
    path = "live_tests/main.rs"
    harness = false
