[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
    anyhow = {workspace = true}
    derive_builder = { workspace = true }
    tokio = { version = "1", features = ["full"] }
    # winit = "0.30"
    wgpu = "22.1.0"
    gui = { workspace = true }
    gpu = { workspace = true }
    graph = { workspace = true }
    node_derive = { workspace = true }
    star = { workspace = true }
    mech = { workspace = true }