[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
    anyhow = {workspace = true}
    derive_builder = { workspace = true }
    tokio = { workspace = true }
    wgpu = { workspace = true }
    gui = { workspace = true }
    gpu = { workspace = true }
    graph = { workspace = true }
    star = { workspace = true }
    mech = { workspace = true }