[package]
    name = "graph"
    version = "0.1.0"
    authors = ["Julian Erickson <julian@rothlabs.com>"]
    edition = "2021"

[features]
    oneThread = []

[dependencies]
    # third party
        # serde
            serde = { version = "1.0", features = ["derive"] }
            serde_json = "1.0"
        # rand
            rand = "0.8.5"
        # regex
            # regex = "1.0.0"
        # dyn-clone
            dyn-clone = "1.0.17"


    # serde-untagged = "0.1.6"

            # erased-serde = {workspace = true}
        # derive
            # derivative = {workspace = true}
            #     #[derive(derivative::Derivative)]
            #     #[derivative(Clone(bound = ""))]
