[workspace]
    members = [
        "app",
        "gpu", 
        "mech", 
        "gui", 
    ]
    resolver = "2" 

[workspace.dependencies]
    anyhow = "1.0"
    tokio = { version = "1", features = ["full"] }
    derive_builder = "0.20.1"
    graph = { path = "../core/graph" }
    node_derive = { path = "../core/node_derive" }
    gpu = { path = "gpu" }
    gui = { path = "gui" }
    mech = { path = "mech" }