[package]
    name = "gui"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    anyhow = { workspace = true }
    derive_builder = { workspace = true }
    wgpu = "22.1.0"
    winit = "0.30"
    tokio = { version = "1", features = ["full"] }
    graph = { path = "../../core/graph" }
    node_derive = { workspace = true }
    gpu = { path = "../gpu" }