[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
    anyhow = { workspace = true }
    derive_builder = { workspace = true }
    wgpu = "22.1.0"
    bytemuck = "1.18.0"
    flume = "0.11.0"
    graph = { path = "../../core/graph" }
    node_derive = { workspace = true }
    star = { path = "../../core/star" }

[dev-dependencies]
    wasm-bindgen-test = "0.3.43"

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
#     winit = "0.30"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
#     dom = { path = "../../web/dom" }    