[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
    anyhow = "1.0"
    derive_builder = "0.20.1"
    wgpu = "22.1.0"
    bytemuck = "1.18.0"
    flume = "0.11.0"
    graph = { path = "../../core/graph", default-features = false, features = ["oneThread"] }
    dom = { path = "../../web/dom" }
    node_derive = { path = "../../core/node_derive" }
    star = { path = "../../core/star" }

[dev-dependencies]
    wasm-bindgen-test = "0.3.43"